# Generated by Django 5.1.5 on 2025-01-18 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='place.state')),
            ],
        ),
        migrations.CreateModel(
            name='VisitingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('popularity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='visiting_places/')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_places', to='place.district')),
            ],
        ),
    ]
